### ISSUE TITLE
main does not compile: WellKnownResource imports bean packages that are never generated

### ISSUE THREAD

**Issue by Aarti-panchal01** [Apicurio/apicurio-registry#9457]
`main` has failed to build on every push since 895a23a80 (#8847), including the current tip 584c71621. `Build Java Application (no tests)` fails to compile the `app` module:

```
app/.../mcptools/rest/beans/McpCompatibleToolsResults.java:[14,18] cannot find symbol: class McpToolSearchResult
app/.../rest/wellknown/WellKnownResource.java:[3,43] package io.apicurio.registry.a2a.rest.beans does not exist
app/.../rest/wellknown/WellKnownResourceImpl.java:[21,48] cannot find symbol: class McpToolSearchResult
```

#8847 changed these imports in `WellKnownResource.java` and `WellKnownResourceImpl.java`:

```diff
-import io.apicurio.registry.rest.v3.beans.AgentSearchResults;
-import io.apicurio.registry.rest.v3.beans.McpToolSearchResults;
+import io.apicurio.registry.a2a.rest.beans.AgentSearchResults;
+import io.apicurio.registry.mcptools.rest.beans.McpToolSearchResults;
```

Neither package is produced. The codegen executions in `common/pom.xml` declare `io.apicurio.registry.rest.v3`, `io.apicurio.registry.rest.v2` and `io.apicurio.registry.types.webhooks`, so the schemas that `openapi.json` declares for `AgentSearchResults`, `McpToolSearchResult` and `McpToolSearchResults` are generated into `io.apicurio.registry.rest.v3.beans`. The sibling `V3WellKnownResource.java` still imports them from there and compiles.

`McpCompatibleToolsResults.java` was added by hand under `io.apicurio.registry.mcptools.rest.beans` and references a `McpToolSearchResult` in that same package. No such class exists anywhere in the tree.

I am not sure which way this is meant to be resolved, so I would rather ask than guess: were the per-feature bean packages intended, needing codegen executions added for them, or should those imports go back to `io.apicurio.registry.rest.v3.beans`? Happy to send the fix once someone confirms the intent.

One thing worth noting about the blast radius: because PR builds check out `refs/pull/N/merge`, this also fails unrelated PRs regardless of their contents, and there is nothing the author of such a PR can push to clear it.

**Comment by Nachiket-Roy** [comment]
Reported the same in #9456 . Thanks for looking into it

**Comment by Aarti-panchal01** [comment]
Duplicate of #9456, which was filed three minutes before this one — I missed it while writing this up.

The break was fixed on `main` by 8d4bb63de (pushed directly by @EricWittmann), which updates the imports in `WellKnownResource` / `WellKnownResourceImpl` after #8803 moved the beans. So there is nothing outstanding here, and #9456 carries the same detail. Closing.

Thanks @Nachiket-Roy for the pointer.
