### ISSUE TITLE
Converter distribution no longer works with 1.2.0.Final

### ISSUE THREAD

**Issue by jpechane** [Apicurio/apicurio-registry#500]
Follow https://github.com/debezium/debezium-examples/tree/master/tutorial#json-format but change the version in dockerfile file to 1.2.0.Final. The connector start will fail with 

```
connect_1    | java.lang.NoClassDefFoundError: org/eclipse/microprofile/rest/client/RestClientBuilder
connect_1    | 	at io.apicurio.registry.client.GenericClient$ServiceProxy.lambda$invoke$0(GenericClient.java:193)
connect_1    | 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
connect_1    | 	at io.apicurio.registry.client.GenericClient$ServiceProxy.invoke(GenericClient.java:191)
connect_1    | 	at com.sun.proxy.$Proxy39.updateArtifact(Unknown Source)
connect_1    | 	at io.apicurio.registry.utils.serde.strategy.AutoRegisterIdStrategy.initialLookup(AutoRegisterIdStrategy.java:32)
connect_1    | 	at io.apicurio.registry.utils.serde.strategy.AbstractCrudIdStrategy.findId(AbstractCrudIdStrategy.java:50)
connect_1    | 	at io.apicurio.registry.utils.converter.ExtJsonConverter.fromConnectData(ExtJsonConverter.java:95)
connect_1    | 	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$1(WorkerSourceTask.java:292)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:292)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:321)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:245)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
connect_1    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect_1    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect_1    | 	at java.base/java.lang.Thread.run(Thread.java:834)
connect_1    | Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.rest.client.RestClientBuilder
connect_1    | 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
connect_1    | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
connect_1    | 	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
connect_1    | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
connect_1    | 	... 22 more
```

**Comment by EricWittmann** [comment]
We need an automated test for this.

**Comment by jpechane** [comment]
@EricWittmann Please take a look at https://github.com/debezium/debezium/pull/1518 There is a rudimentary test you could consider to use as the basis for your test.

**Comment by EricWittmann** [comment]
OK thanks @jpechane .

@famartinrh or @im-konge - would either of you be able to take a stab at testing the Kafka Converter distribution?  Nothing fancy just a smoke test of the distro we're producing.  Mostly to verify we have the right dependencies included.

**Comment by im-konge** [comment]
@EricWittmann we will take a look at it.

**Comment by im-konge** [comment]
@jpechane @EricWittmann we found with @famartinrh some issues in Kafka testcontainers etc. and @famartinrh already fixed some issues -> your tests are working properly?

**Comment by jpechane** [comment]
@im-konge Hi, for us Kafka containers works fine but we are not stressing it much so it is possible some uncovered issues exist.

**Comment by EricWittmann** [comment]
I believe this is now fixed.  Fixed in this PR:  https://github.com/Apicurio/apicurio-registry/pull/520
